### ISSUE TITLE
Suggestion: config for disabling function in creative mode

### ISSUE THREAD

**Issue by Samekichi** [Szum123321/elytra_swap#14]
Currently the mod works fine in survival mode and helps me a lot. 

However, it'll also work when falling down in creative mode (especially when disable fly mode and fall) and may cause some inconvenience or incompatibility (e.g. switching from survival to creative for some purposes with elytra in my inventory, and the elytra will make me move forward instead of falling vertically after disabling fly mode). 

Therefore, it may be better to have an option in config file (mod menu would be even greater) for disabling the function in creative mode. 

Finally, thx for this useful mod!

**Comment by Szum123321** [comment]
There is keybind for doing just that! Just press p to enable and disable elytra Swap for yourself.

**Comment by MeeniMc** [comment]
I do think that in most instances, people want this mod to be OFF in creative mode, as it causes weird jumps in creative flying mode. 

It should switch itself OFF upon entering creative mode, since it is not useful in that case.
It should switch itself back to whatever mode was toggled with the 'p' key upon entering survival/adventure modes.
