### ISSUE TITLE
The mod doesn't work on version 1.16.1 in server

### ISSUE THREAD

**Issue by MimicFS** [Szum123321/elytra_swap#16]
Downloaded this mod for version 1.16.1, downloaded Fabric and the rest of the elements for 1.16.1. Starting the version, I go to the server and the mod does not work. When I click the button to activate it, nothing is written in the chat. The mod only works in a single world. But it doesn't work on the server. What to do?

**Comment by Szum123321** [comment]
This mod has to be installed on the server.

**Comment by hugeblank** [comment]
From what I understand you're refusing to make this mod client side only because it wouldn't be fair on servers. How does this make any sense when everyone has access to the mod, its source, fabric's own source, installation tutorials, etc? I run a vanilla server with my friends and allow for players to install client side mods for an enriched experience. Having this mod be client-side only *especially* when it could be client side only just makes logical sense in my use case. You're really limiting the audience that's going to utilize this mod.

**Comment by Szum123321** [comment]
I think you missed the point. I'm not here to please anyone. I'm creating those mods because I like to do so. 

Also, keeping it server-side only makes sense as there aren't many people who are willing to spend their time turning this mod into a cheating tool. 

And why current state of my mod is even a problem in your case? You said, you run that server, so why won't you use it as it is?
